# Generated by Django 3.2.13 on 2022-06-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
