# Generated by Django 3.2.13 on 2022-06-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0006_auto_20220609_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='date',
            field=models.DateField(),
        ),
    ]
