# Generated by Django 3.2.13 on 2022-06-10 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0008_alter_play_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlayComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_play_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_list_comments', to='forums.play')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
