# Generated by Django 3.2.13 on 2022-06-10 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0009_auto_20220610_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['date']},
        ),
    ]
