# Generated by Django 3.2.13 on 2022-06-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
