# Generated by Django 3.2.13 on 2022-06-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0014_alter_play_setup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
