# Generated by Django 3.2.13 on 2022-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_remove_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
